### ISSUE TITLE
Accessible search button

### ISSUE THREAD

**Issue by dreamwhisper** [brandid/course-maker-pro#13]
The search widget shows a square button with no readable text when tabbing with the keyboard. It's due to the screen reader text CSS and this:

```css
.widget_search .search-form input[type="submit"] {
    height: 20px;
    width: 20px;
}
```
![search](https://user-images.githubusercontent.com/1271053/73196870-65ae1600-40fe-11ea-828b-6309594c0cad.gif)

For accessibility, the button could be shown on focus similar to https://github.com/studiopress/genesis-sample/blob/develop/style.css#L540
